name: working_pacemaker
description: A Flutter demo application for mobile and web.

version: 1.0.0+1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  async: ^2.3.0
  charts_flutter: ^0.8.1
  cupertino_icons: ^0.1.2
  device_info: ^0.4.1+1
  firebase_analytics: ^5.0.2
  flutter_icons: ^0.3.1
  intl: ^0.16.0
  meta: ^1.0.0
  path: ^1.6.4
  path_provider: ^1.4.2
  pedantic: ^1.8.0+1
  percent_indicator: ^2.1.1+1
  provider: ^3.0.0
  quiver: ^2.0.0
  rxdart: ^0.22.5
  shared_preferences: ^0.5.4
  soundpool: ^0.5.3
  stream_transform: ^0.0.20
  tuple: ^1.0.0

dev_dependencies:
  fake_async: ^1.0.1
  flutter_driver:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.7
  mockito: ^4.1.1
  test:

flutter:
  uses-material-design: true
  assets:
    - asset/audio/sound/count_zero.mp3
    - asset/audio/sound/countdown.mp3
    - asset/audio/sound/pace_making.mp3

flutter_icons:
  android: true
  ios: true
  image_path: "asset/image/app_icon_512x512.png"